### ISSUE TITLE
Private repository

### ISSUE THREAD

**Issue by Sergei-TOL** [actions/container-prebuilt-action#17]
Does this method work with private repos? 

I want to create an action for my organization in private repo
but when I run Example Workflow I see this error about "unauthorized":

![image](https://github.com/user-attachments/assets/953dcd64-a485-49da-8a79-86c11f44f5ef)

**Comment by urbanautomaton** [comment]
I also have this problem, but for the full use case of invoking the action from another private repo within my organization (I don't have the example workflow running).

Following [the relevant docs](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#github-actions-access-for-packages-scoped-to-organizations) I granted read access to the calling repo in the docker container package settings, but it can't pull the image.

Package settings for the prebuilt image:

<img width="1261" alt="Screenshot 2024-07-30 at 19 50 39" src="https://github.com/user-attachments/assets/7bae575c-34d8-494c-a568-2c8792f7c3d7">

Workflow results:

<img width="1176" alt="Screenshot 2024-07-30 at 19 53 57" src="https://github.com/user-attachments/assets/572966bb-9d36-4856-af11-6ac65021d1c4">

**Comment by ncalteen** [comment]
Unfortunately, it doesn't appear this is supported at this time :( The closest equivalent I could find was private registry support for jobs and services (https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/)

**Comment by OR13** [comment]
@ncalteen do you know if its possible to use a private package with github actions?

for example:

```yaml
runs:
  using: 'docker'
  image: docker://ghcr.io/org/repo:main
  args:
    - ${{ inputs.name }}
```

**Comment by ncalteen** [comment]
At the moment, I don't believe this is supported. However, one potential workaround would be to use a [job/service container](https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/) instead. They do support private registries.

In effect, the entire job would be running on the container, instead of a single step. I hope that helps!
